package es.unizar.smartcampuz.application.auth;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * An entity Credential composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "users")
public class Credential {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's email
    @NotNull
    @Column(unique=true)
    private String email;

    // The user's password
    @NotNull
    private String password;

    // The user's role
    @NotNull
    private String role;


    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Credential() { }

    public Credential(long id) {
        this.id = id;
    }

    public Credential(@NotNull String email, @NotNull String password, @NotNull String role) {
        this.email = email;
        this.password = password;
        this.role = role;
    }

    public boolean checkPassword(String givenPass){
        return this.password.equals(givenPass);
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
} // class Credential
